// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBvSPWH0neAPhMD4QJXgTx9Vj53DXo4l5I",
    authDomain: "auth-588b6.firebaseapp.com",
    projectId: "auth-588b6",
    storageBucket: "auth-588b6.firebasestorage.app",
    messagingSenderId: "269617228424",
    appId: "1:269617228424:web:52b9dbe85f9230efdd4d3d",
    measurementId: "G-Q898X6BHPS",
    databaseURL:
        "https://auth-588b6-default-rtdb.europe-west1.firebasedatabase.app", // ← ADDED
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBvSPWH0neAPhMD4QJXgTx9Vj53DXo4l5I",
    authDomain: "auth-588b6.firebaseapp.com",
    projectId: "auth-588b6",
    storageBucket: "auth-588b6.firebasestorage.app",
    messagingSenderId: "269617228424",
    appId:
        "1:269617228424:android:52b9dbe85f9230efdd4d3d", // ← CHANGED web → android
    databaseURL:
        "https://auth-588b6-default-rtdb.europe-west1.firebasedatabase.app", // ← ADDED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBvSPWH0neAPhMD4QJXgTx9Vj53DXo4l5I",
    authDomain: "auth-588b6.firebaseapp.com",
    projectId: "auth-588b6",
    storageBucket: "auth-588b6.firebasestorage.app",
    messagingSenderId: "269617228424",
    appId: "1:269617228424:ios:52b9dbe85f9230efdd4d3d", // ← CHANGED web → ios
    databaseURL:
        "https://auth-588b6-default-rtdb.europe-west1.firebasedatabase.app", // ← ADDED
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBvSPWH0neAPhMD4QJXgTx9Vj53DXo4l5I",
    authDomain: "auth-588b6.firebaseapp.com",
    projectId: "auth-588b6",
    storageBucket: "auth-588b6.firebasestorage.app",
    messagingSenderId: "269617228424",
    appId:
        "1:269617228424:macos:52b9dbe85f9230efdd4d3d", // ← CHANGED web → macos
    databaseURL:
        "https://auth-588b6-default-rtdb.europe-west1.firebasedatabase.app", // ← ADDED
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBvSPWH0neAPhMD4QJXgTx9Vj53DXo4l5I",
    authDomain: "auth-588b6.firebaseapp.com",
    projectId: "auth-588b6",
    storageBucket: "auth-588b6.firebasestorage.app",
    messagingSenderId: "269617228424",
    appId:
        "1:269617228424:windows:52b9dbe85f9230efdd4d3d", // ← CHANGED web → windows
    databaseURL:
        "https://auth-588b6-default-rtdb.europe-west1.firebasedatabase.app", // ← ADDED
  );
}
